#!/bin/bash

# Kill all fxClock Java apps I've started.
stopFxClock

# Launch fxClock Java app by desktop.
if [[ $XDG_SESSION_DESKTOP == "KDE" ]]; then
    kioclient exec /usr/share/applications/fxclock.desktop 1>/dev/null 2>/dev/null
fi
if [[ $XDG_SESSION_DESKTOP == "ubuntu:GNOME" ]]; then
    gtk-launch fxclock.desktop
fi
