#!/bin/bash

# Kill all fxClock Java apps I've started.
for PROC_ID in $(pgrep java); do \
    cat /proc/$PROC_ID/cmdline | egrep fxClock 1>/dev/null && \
        [ $USER == $(ps -o user= -p $PROC_ID) ] && \
            kill -15 $PROC_ID; done
